version: "3"

services:
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: unless-stopped
    device_cgroup_rules:
      - 'c 10:200 rwm'
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data/warp:/var/lib/cloudflare-warp

  scraper:
    build: .
    container_name: baha-scraper
    restart: unless-stopped
    depends_on:
      - warp
    ports:
      - "15913:15913"
    environment:
      - PORT=15913
      - HTTP_PROXY=socks5://warp:1080
      - HTTPS_PROXY=socks5://warp:1080
    volumes:
      - ./data/scraper:/app/data
